#!/bin/bash
#$ -l h_rt=240:00:00
#$ -l h_vmem=7.5G
#$ -pe smp 12
#$ -l gpu=1
#$ -l gpu_type=ampere
#$ -wd /data/home/eey362/code/object_relation_transformer/
#$ -j y
#$ -m ea
#$ -o logs/
#$ -l cluster=andrena


# Load modules
module purge

module load python/3.10.7
module load cuda/11.8.0
module load gcc/6.3.0
module load java/1.8.0_382-openjdk

# Activate virtual environment
source .venv/bin/activate

model_name="relation_transformer_bu"

# Eval
python eval.py --dump_images 0 \
	--num_images 5000 \
	--model "/data/scratch/eey362/object_relation_transormer_checkpoints/model.pkl" \
	--infos_path "/data/scratch/eey362/object_relation_transormer_checkpoints/infos_{$model_name}-best.pkl" \
	--image_root "/data/EECS-YuanLab/COCO/img/" \
	--input_json "/data/EECS-YuanLab/COCO/cocotalk.json" \
	--input_fc_dir "/data/EECS-YuanLab/COCO/butd_fc" \
	--input_att_dir "/data/EECS-YuanLab/COCO/butd_att" \
	--input_box_dir "/data/EECS-YuanLab/COCO/butd_box" \
	--input_rel_box_dir "data/cocobu_box_relative/" \
	--input_label_h5 "/data/EECS-YuanLab/COCO/cocotalk_label.h5" \
	--checkpoint_path "/data/scratch/eey362/object_relation_transormer_checkpoints/" \
	--language_eval 1


